export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const LIST_ROUTE = '/list'
export const ANIMAL_ROUTE = '/animal'
export const HOME_ROUTE = '/'